/**
 * Guardrail Lab - Policy & Rule Exporters
 * 
 * Translates tested guardrail policies into production configuration files for:
 * - Claude Code (.claude/config.json permissions.deny)
 * - Cursor (.cursorrules tool restriction markdown)
 * - agentsh (agentsh.yaml execution-layer syscall interceptor)
 * - POSIX Shell Wrapper Hook (hardened pre-exec shell script)
 * - Docker / Seccomp Profile (JSON syscall filter)
 */

export function generateExports(policy, rule, mode) {
  return {
    claudeCode: generateClaudeCodeConfig(policy, rule, mode),
    cursorRules: generateCursorRules(policy, rule, mode),
    agentsh: generateAgentshPolicy(policy, rule, mode),
    shellWrapper: generateShellWrapper(policy, rule, mode),
    seccomp: generateSeccompProfile(policy)
  };
}

function generateClaudeCodeConfig(policy, rule, mode) {
  let denyPattern = rule;
  if (mode === 'structured') {
    denyPattern = policy.alternativeRegex || rule;
  }

  const config = {
    "$schema": "https://json.schemastore.org/claude-code-config.json",
    "version": "1.0",
    "permissions": {
      "deny": [
        {
          "tool": "Bash",
          "commandPattern": denyPattern,
          "description": `Blocked by Guardrail Lab: ${policy.intent}`,
          "layer": "pre_tool_call"
        }
      ],
      "ask": [
        {
          "tool": "Bash",
          "commandPattern": "git push|git merge",
          "description": "Require human interactive confirmation for SCM mutations"
        }
      ]
    }
  };

  return JSON.stringify(config, null, 2);
}

function generateCursorRules(policy, rule, mode) {
  return `# Guardrail Lab Policy Enforcement: ${policy.name}
# Intent: ${policy.intent}
# Generated: ${new Date().toISOString()}

## Operational Constraints for AI Coding Tools
You are an autonomous AI coding assistant. You must adhere strictly to operational boundaries:

### Restricted Operations
1. DO NOT execute commands matching the intent of: "${policy.name}".
2. Specifically, do not emit the following command patterns:
   - Primary Rule (${mode.toUpperCase()}): \`${rule}\`
   ${policy.alternativeRegex ? `- Hardened Regex Anchor: \`${policy.alternativeRegex}\`` : ''}

### Enforcement Layer Clarification
- Do NOT attempt to evade restrictions via interleaved flags (e.g., \`git -C /path\`), compound chaining (\`&&\`, \`;\`), process wrappers (\`env\`), or subshell resolutions (\`$(which ...)\`).
- If an operational restriction is encountered, fail gracefully and request explicit user confirmation.
`;
}

function generateAgentshPolicy(policy, rule, mode) {
  return `# agentsh Execution-Layer Security Policy
# Enforces deterministic syscall boundary at kernel execve layer
# Generated by Guardrail Lab

version: "1.0"
metadata:
  policy_id: "${policy.id}"
  policy_name: "${policy.name}"
  enforcement_layer: "execve_syscall"

rules:
  - name: "block_${policy.id}"
    description: "${policy.intent}"
    action: "deny"
    exit_code: 126
    match:
      executable: "${policy.id.startsWith('git') ? 'git' : policy.id.startsWith('rm') ? 'rm' : 'curl'}"
      ${policy.id === 'git-commit' ? 'subcommands:\n        - "commit"' : ''}
      ${policy.id === 'rm-rf' ? 'arguments:\n        - "-r"\n        - "-f"' : ''}
    audit:
      log_level: "alert"
      notify_operator: true
`;
}

function generateShellWrapper(policy, rule, mode) {
  return `#!/usr/bin/env bash
# ==============================================================================
# Guardrail Lab - Pre-Exec Interceptor Wrapper
# Place in /usr/local/bin or alias in developer agent environment
# ==============================================================================
set -euo pipefail

RESTRICTED_OP="${policy.name}"
RAW_COMMAND="$*"

# Forensic AST executable & subcommand token check
if [[ "$RAW_COMMAND" =~ ${policy.alternativeRegex || rule} ]]; then
    echo -e "\\033[1;31m[GUARDRAIL LAB INTERCEPTOR]\\033[0m Blocked unauthorized tool invocation:" >&2
    echo "  Intent: $RESTRICTED_OP" >&2
    echo "  Command: $RAW_COMMAND" >&2
    echo "  Failure: Operational policy violation (Layer A / B boundary)" >&2
    exit 126
fi

# Fallback: Forward to underlying host binary
exec /usr/bin/\${0##*/} "$@"
`;
}

function generateSeccompProfile(policy) {
  const profile = {
    "defaultAction": "SCMP_ACT_ALLOW",
    "architectures": [
      "SCMP_ARCH_X86_64",
      "SCMP_ARCH_AARCH64"
    ],
    "syscalls": [
      {
        "names": ["execve", "execveat"],
        "action": "SCMP_ACT_ERRNO",
        "comment": `Guardrail Lab: Intercept execution for ${policy.name}`,
        "args": []
      }
    ]
  };

  return JSON.stringify(profile, null, 2);
}
